<?php

namespace XelSeleniusBundle\Repository;

/**
 * BuildingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingsRepository extends \Doctrine\ORM\EntityRepository
{
}
