<?php

namespace XelSeleniusBundle\Repository;

/**
 * Buildings_TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Buildings_TypeRepository extends \Doctrine\ORM\EntityRepository
{
}
