<?php

namespace XelSeleniusBundle\Repository;

/**
 * PlanetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetsRepository extends \Doctrine\ORM\EntityRepository
{
}
